In [1]:
import numpy as np

Создание массива

In [3]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

Вычисление среднего в столбцах

In [5]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

Вычитание среднего из значений

In [6]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Вычисление ковариации

In [11]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
covariation = a_centered_sp / 4
covariation

2.0

Транспонирование матрицы

In [14]:
a_T = a.T
a_T

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

Высиление ковариации вторым способом

In [17]:
b = np.cov(a_T)
b

array([[1. , 2. ],
       [2. , 4.3]])

In [18]:
b[0, 1]

2.0

### Вывод ковариации равны